# Generated by Django 3.0.2 on 2020-02-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='posts',
        ),
    ]
